### ISSUE TITLE
Ontoportal Multilingualism support

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal/ontoportal-project#17]
## Context
In this current first semester of 2023, we plan for our Agroportal team, to work in the Multilingualism in Agroportal.  For now, it will be mostly an intern @haddadzineddine and me (@syphax-bouazzouni) that will work on it, for the next 6 months. But we are open if people want to collaborate or work with us on it in parallel.

Anyway we will be happy to catch up and implement (if possible) your requirements,

## References

- [JSON-LD String Internationalization](https://www.w3.org/TR/json-ld11/#string-internationalization)
- https://github.com/ncbo/goo/issues/95
- https://github.com/ncbo/ontologies_linked_data/issues/91
- https://github.com/ncbo/goo/pull/118
- https://github.com/ontoportal/goo/issues/1

## Goal

Make Ontoportal/Agroportal UI and API multilingual, where a user can choose a unique language to display or instead all of them.
### Targeted state in the API
Be compliant with [JSON-LD](https://www.w3.org/TR/json-ld11/#string-internationalization), and display the following in the API

#### For unique language display
<img width="837" alt="image" src="https://user-images.githubusercontent.com/29259906/213648199-21ab8f39-73dc-4977-a0dd-78ed3a9b2578.png">

#### For multiple language display
 
![image](https://user-images.githubusercontent.com/29259906/213647987-656fd37d-4d61-42e3-b0be-e94eb2cf63e4.png)

### Targeted state in the UI
To be define

## Our roadmap 

See https://github.com/agroportal/project-management/issues/307

**Comment by syphax-bouazzouni** [comment]
FYI: @ontoportal/bioportal , @ontoportal/ecoportal , @ontoportal/agroportal , @ontoportal/cognizone , @ontoportal/earthportal, @ontoportal/industryportal, @ontoportal/medportal

Please put here if you have any specific requirements about this topic.

**Comment by xeniacs** [comment]
Thanks for opening this Syphax!
I see two separate fields for improvement in multilingual support:

### 1. Ontology Display
Ideally, I would like to have ontologies displayed by default in the language that the author prefers. Then, if it contains labels in other languages, a user could switch the taxonomy displayed on the left-hand side to another language. Also the properties (if they have labels in other languages) on the right-hand side could be changed together with the taxonomic view.

If the ontology author does not specify a preferred language of display, the default should be the language chosen by the portal administration. So, English in our case, French for SIFR, Chinese for MedPortal, etc.

If the default language of the portal cannot be respected by the ontology because all its labels are in another language and the author has not specified a preferred language for display, then the first parsed skos:prefLabel / rdfs:label could be the one displayed.

### 2. Search for terms (_"Jump To"_)
I'd like the search functionality right above the taxonomic view of the ontology to work with all labels, therefore in all languages present in the ontology. This is what currently happens in the Search Tool, it works with all labels.

How do these suggestions sound?

**Comment by syphax-bouazzouni** [comment]
Close as done in https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/v2.7.0, discussion about merging it to the main Ontoportal branch will be discussed here #37
