### ISSUE TITLE
deploy a demo ontoportal site

### ISSUE THREAD

**Issue by alexskr** [ontoportal/ontoportal-project#23]
Deploy a demo instance of the OntoPortal application to showcase the technology.

**Comment by syphax-bouazzouni** [comment]
Thanks, @alexskr for the work done.

Just to give more details and context for people who would read this issue.

### Context
This was an action item decided in the LIRMM visits at Stanford (2023), the requirements were to :

1. Have a server deployed with the latest branches on OntoPortal GitHub, that can be used as a demo server for people who want to test the OntoPortal technology. It can be http://demo.ontoportal.org and http://demodata.ontoportal.org and http://demosparql.ontoportal.org and all must be open to the public. 

2. The content needs to be reset regularly (every couple of months) to have a fresh demo server each time.

3. Possibly automate the deployment so that it's in sync with the master branches on OntoPortal GitHub
