### ISSUE TITLE
JSON API output has id and @id fields set as either NULL or empty

### ISSUE THREAD

**Issue by chris-day** [ontoportal/ontoportal-project#28]
**Describe the bug**
When using the REST API, the resultant output in JSON contains NULL or empty/blank id and @id fields. These should be valid URI.

**To Reproduce**
Call mappings API with MEDDRA (nice and small)

**Expected behavior**
The id and @id fields contain a valid URI

**Comment by jonquet** [comment]
This is "normal" .. not that I am fan about it but it has always been like this since the implementation of the mapping repository 10 years ago. The mappings without ids are the one that are not "materialized". 
See more info about mappings here: 
https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/mappings-JYGyUrAJkw

We will eventually need to get rid of this behaviour the day we will re-implement the whole mapping repository.

**Comment by chris-day** [comment]
@jonquet - Surely a dummy URI would be sufficient?
