### ISSUE TITLE
Filter API Classes with a language parameter

### ISSUE THREAD

**Issue by luddaniel** [ontoportal/ontoportal-project#57]
**Describe the bug**
While using API `/ontologies/{ontology}/classes/{uri}` query parameter `language` is no longuer working with multiple languages.

**To Reproduce**
Example: https://data.agroportal.lirmm.fr/ontologies/GACS/classes/http%3A%2F%2Fid.agrisemantics.org%2Fgacs%2FC28729?language=fr,en
Result: `"prefLabel": null,`

**Expected behavior**
`prefLabel` and `synonym` should only contain the specified language.
Expected Result for `?language=fr,en` : 
```json
"prefLabel": {
	"fr": "Phylloxera",
	"en": "Phylloxera"
},
"synonym": {
	"en": [
		"Daktulosphaira (phylloxera)"
	],
	"fr": [
		"Daktulosphaira (phylloxera)"
	]
},
```

**Additional context**
Please note that : 

- `language=all`
- `language=fr`
- `language=en`

are still working.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/goo/pull/61
Deployed in Staging environment https://data.stageportal.lirmm.fr/ontologies/INRAETHES/classes/http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fc_25056?lang=fr,en&display=prefLabel,synonym&display_links=false&display_context=false 
<img width="754" alt="image" src="https://github.com/ontoportal/ontoportal-project/assets/29259906/57bf900f-35a0-40b7-9b3c-1125f5009934">


@luddaniel  this fix will come in the next release of AgroPortal  (mid-July)
